#!/usr/bin/env bash

CHECKPOINT_FILE="$HOME/.dotfiles-checkpoint"
CHECKPOINT_STAGE=""
RESUME_MODE=0

checkpoint_save() {
  local stage="$1"
  cat > "$CHECKPOINT_FILE" <<EOF
# Dotfiles Checkpoint - $(date)
CHECKPOINT_STAGE="$stage"
INSTALL_ZSH=$INSTALL_ZSH
INSTALL_FISH=$INSTALL_FISH
INSTALL_NUSHELL=$INSTALL_NUSHELL
INSTALL_OH_MY_ZSH=${INSTALL_OH_MY_ZSH:-0}
INSTALL_STARSHIP=${INSTALL_STARSHIP:-0}
INSTALL_OH_MY_POSH=${INSTALL_OH_MY_POSH:-0}
INSTALL_POWERLEVEL10K=${INSTALL_POWERLEVEL10K:-0}
GIT_CONFIGURE=${GIT_CONFIGURE:-0}
SELECTED_CLI_TOOLS=(${SELECTED_CLI_TOOLS[*]})
SELECTED_IA_TOOLS=(${SELECTED_IA_TOOLS[*]})
SELECTED_TERMINALS=(${SELECTED_TERMINALS[*]})
SELECTED_RUNTIMES=(${SELECTED_RUNTIMES[*]})
SELECTED_NERD_FONTS=(${SELECTED_NERD_FONTS[*]})
SELECTED_IDES=(${SELECTED_IDES[*]})
SELECTED_BROWSERS=(${SELECTED_BROWSERS[*]})
SELECTED_DEV_TOOLS=(${SELECTED_DEV_TOOLS[*]})
SELECTED_DATABASES=(${SELECTED_DATABASES[*]})
SELECTED_PRODUCTIVITY=(${SELECTED_PRODUCTIVITY[*]})
SELECTED_COMMUNICATION=(${SELECTED_COMMUNICATION[*]})
SELECTED_MEDIA=(${SELECTED_MEDIA[*]})
SELECTED_UTILITIES=(${SELECTED_UTILITIES[*]})
EOF
}

checkpoint_load() {
  if [[ -f "$CHECKPOINT_FILE" ]]; then
    # shellcheck source=/dev/null
    source "$CHECKPOINT_FILE"
    return 0
  fi
  return 1
}

checkpoint_clear() {
  [[ -f "$CHECKPOINT_FILE" ]] && rm -f "$CHECKPOINT_FILE"
}

checkpoint_exists() {
  [[ -f "$CHECKPOINT_FILE" ]]
}
